#!/bin/bash

function getFlags(){
	if [[ $2 ]]; then
		appDir="$2"
	fi
	if [[ $1 ]]; then
		appExec="$1"
	else
		exit
	fi
	main "${ELECTRON_OPTIONS}"
}

function main(){
	bwrap --symlink usr/lib /lib \
	--symlink usr/lib64 /lib64 \
	--symlink usr/bin /bin \
	--symlink usr/bin /sbin \
	--ro-bind /usr /usr \
	--ro-bind /etc /etc \
	--dev /dev \
	--dev-bind /dev/dri /dev/dri \
	--proc /proc \
	--ro-bind /sys/dev/char /sys/dev/char \
	--ro-bind /sys/devices /sys/devices \
	--ro-bind /run/dbus /run/dbus \
	--dir "$XDG_RUNTIME_DIR" \
	--chmod 0700 "$XDG_RUNTIME_DIR" \
	--bind "$XDG_RUNTIME_DIR/wayland-0" "$XDG_RUNTIME_DIR/wayland-0" \
	--bind "$XDG_RUNTIME_DIR/pipewire-0" "$XDG_RUNTIME_DIR/pipewire-0" \
	--bind "$XDG_RUNTIME_DIR/pulse" "$XDG_RUNTIME_DIR/pulse" \
	--bind "$XDG_RUNTIME_DIR/bus" "$XDG_RUNTIME_DIR/bus" \
	--tmpfs /tmp \
	--bind "$HOME" "$HOME" \
	--ro-bind "${appDir}" "${appDir}" \
	electron "${appDir}"/${appExec} --enable-features=UseOzonePlatform --ozone-platform=wayland --use-vulkan --ignore-gpu-blocklist --enable-zero-copy --enable-features=VaapiVideoDecoder --enable-features=VaapiIgnoreDriverChecks "$@"
}

getFlags "$@"
